---
title: "Football Visualisations"
author: "Christoph Plachutta"
date: "2022-11-18"
output: html_document
---

```{r, setup, echo=FALSE}
knitr::opts_chunk$set(
  message = FALSE, 
  warning = FALSE, 
  tidy=FALSE,     # display code as typed
  size="small")   # slightly smaller font for code
options(digits = 3)

# default figure size
knitr::opts_chunk$set(
  fig.width=6.75, 
  fig.height=6.75,
  fig.align = "center"
)
```

```{r libraries, include=FALSE}
library(tidyverse)
library(extrafont)
library(vroom)
library(ggtext)
library(gapminder)
library(ggrepel)
library(patchwork)
library(gghighlight)
library(skimr)
library(lubridate)
library(jpeg)
library(png)
library(patchwork)
library(maps)
library(ggstream)
library(ggsankey)
library(ggmap)
library(tmap)
library(tmaptools)
library(hrbrthemes)
library(mapview)
library(viridis)
library(sf)
library(here)
library(countrycode)
library(ggspatial)
library(giscoR)
library(rasterpic)
library(rnaturalearth)
library(rnaturalearthdata)
library(rgdal)
library(rgeos)
library(ggpmisc)

loadfonts(device="win")
# loadfonts(device="pdf") if you have a mac

```


```{r, load data}

players_21 <- read_delim("data/2122players.csv", 
                           delim = ";", escape_double = FALSE, trim_ws = TRUE)
players_22 <- read_delim("data/2223players.csv", 
                         delim = ";", escape_double = FALSE, trim_ws = TRUE)
teams_21 <- read_delim("data/2122teams.csv", 
                         delim = ";", escape_double = FALSE, trim_ws = TRUE)
teams_22 <- read_delim("data/2223teams.csv", 
                       delim = ";", escape_double = FALSE, trim_ws = TRUE)

players_21 <- players_21 %>% 
  mutate(Pos = substr(Pos,1,2))
unique(players_21$Pos)

players_22 <- players_22 %>% 
  mutate(Pos = substr(Pos,1,2))
```

```{r, add player data and clean}

# Load all CSV files of different years into R
fifa_players <- list.files(path = "data/players",  # Identify all CSV files
                       pattern = "*.csv", full.names = TRUE) %>% 
  lapply(read_csv) %>%                              # Store all files in list
  bind_rows                                         # Combine data sets into one data set 

# Define leagues of interest
leagues = c("German 1. Bundesliga", "English Premier League", "Italian Serie A", "Spain Primera Division", "French Ligue 1")

# Clean data
fifa_players_clean <- fifa_players %>% 
  filter(league_name %in% leagues) %>% # Filter out all players not in the league of interest
  distinct(sofifa_id, .keep_all = TRUE) %>% # Filter out duplicate players due to multiple years of data
  mutate(nationality_name = replace(nationality_name, nationality_name == "Korea DPR", "Korea Republic")) # combine Korea DPR and Korea Republic

# Calculate number of players per nation
nations_n <- fifa_players_clean %>% 
  group_by(nationality_name) %>% # group for summarization
  # adjust names to match sf data
  mutate(nationality_name = recode(nationality_name, 
                                   "Bosnia and Herzegovina" = "Bosnia and Herz.",
                                   "Brunei Darussalam" = "Brunei",
                                   "Cape Verde Islands" = "Cape Verde",
                                   "Central African Republic" = "Central African Rep.",
                                   "China PR" = "China",
                                   "Congo DR" = "Dem. Rep. Congo",
                                   "Curacao" = "Curaçao",
                                   "Czech Republic" = "Czech Rep.",
                                   "Dominican Republic" = "Dominican Rep.",
                                   "England" = "United Kingdom",
                                   "Equatorial Guinea" = "Eq. Guinea",
                                   "Faroe Islands" = "Faeroe Is.",
                                   "Guinea Bissau" = "Guinea-Bissau",
                                   "Korea Republic" = "Dem. Rep. Korea",
                                   "Macau" = "Macao",
                                   "North Macedonia" = "Macedonia",
                                   "Northern Ireland" = "Ireland",
                                   "Republic of Ireland" = "Ireland",
                                   "Saint Kitts and Nevis" = "St. Kitts and Nevis",
                                   "Scotland" = "United Kingdom",
                                   "South Sudan" = "Sudan",
                                   "Wales" = "United Kingdom")) %>% 
  summarize(count = n()) %>% # calculate sum
  mutate(africa = ifelse(nationality_name %in% c("Senegal", "Côte d'Ivoire", "Ghana", "Morocco", "Nigeria", "Cameroon", "Algeria", "Mali", "Dem. Rep. Congo"), TRUE, FALSE)) %>% # create column to highlight African nations of interest
  rename(name = nationality_name) %>% # rename columns for later joining
  filter(!name %in% c("Germany", "France", "Italy", "United Kingdom", "Spain")) # deselect values of league host countries due to unnaturally high value

```

```{r create map with player density}

# Create map of the world
map <- ne_countries(scale = "medium", returnclass = "sf") %>%
  dplyr::select(name, iso_a3, geometry) %>%
  filter(!name %in% c("Greenland", "Antarctica"))

# Create map filled with count of players per nation
players_by_country <- map %>% 
  left_join(nations_n, by = "name") %>% # join map data with calculation of player count
  # Create plot
  ggplot() +
    geom_sf(mapping = aes(geometry = geometry, fill = log10(count), colour = africa)) + # colour to highlight African countries of interest
    coord_sf(crs = "+proj=robin") +  # change coords for more accurate representation of map
    scale_color_manual(values = c("#838383", "#04f5ff"), guide = "none") + # define manual colours for highlight African countries of interest
    scale_fill_gradient(
    low = "#E4F2E7",
    high = '#00381F',
    na.value = "grey60",) + # change gradient fill colours
    theme(panel.background = element_blank(), # remove background
          axis.ticks = element_blank(), # remove axis ticks
          legend.title = element_text(size = 9), # adjust legend title size
          legend.text = element_text(size = 8), # adjust legend text size
          axis.text = element_blank(), # remove axis labels
          plot.title.position = "plot", # left align title
          plot.title = element_textbox_simple(size=15)) + # change title size
  # Change labels
  labs(title = "<b>Several<span style='color:#04f5ff'> African countries</span> seem to produce top-tier football players</span></b><br>
         <span style = 'font-size:12pt'>Number of unique players in the top 5 European leagues between 2015 and 2022",
         fill = "Playercount (log10)",
         x = "",
         y = "") +
  xlim(-13000000,15000000) # change span of x axis

# View map
players_by_country

# Save plot
ggsave(
  plot = players_by_country,
  filename = "players_by_country.png",
  bg = "transparent"
)

```


```{r map of best teams per country}

# Download team spi data
team_spi <- read.csv("data/spi_global_rankings.csv", header = TRUE) %>% 
  rename(name = country)

# Define countries of Europe
eur_countries <- c("Austria","Belgium","Bulgaria","Croatia","Cyprus",
                    "Czech Rep.","Denmark","Estonia","Finland","France",
                    "Germany","Greece","Hungary","Ireland","Italy","Latvia",
                    "Lithuania","Luxembourg","Malta","Netherlands","Norway", "Poland",
                    "Portugal","Romania","Slovakia","Slovenia","Spain",
                    "Sweden", "Switzerland", "United Kingdom")

# Import data on team logo pngs
team_logos <- read.csv("data/team_logos.csv")

# Find top team based on SPI per country
team_spi_top <- team_spi %>% 
  group_by(name) %>% # group for summarization
  slice_max(spi, n = 1) %>% # find top team per country
  filter(name %in% eur_countries) %>% # only select european teams
  left_join(team_logos, by = "team") # join logo png data for later fill

# Get map of Europe data
eu_map <- map %>% 
  filter(name %in% eur_countries)

# Join map geom data with png and SPI data
plot <- eu_map %>% 
  left_join(team_spi_top, by = "name")

# Create map of Europe
actual_map <- eu_map %>% 
  ggplot() +
    geom_sf(color = "black", fill = "#E4F2E7") + # Define border and fill colours
    coord_sf(crs = "+proj=robin") + # change coords to create more accurate map
    theme_minimal() + # Change theme
    theme(panel.grid = element_blank(), # remove gridlines
          panel.background = element_blank(), # remove background
          plot.title.position = "plot", # left align title
          plot.title = element_textbox_simple(size=15)) + # change title size) +
  # Adjust labels
    labs(title = "<b>Every country has its best-performing team, but there are gaps between nations </b><br>
          Logos of the currently best performing teams according to fivethirtyeight per country")

# Create loop to download and add logos to map
for (row in 1:nrow(team_logos)) {
  if(team_logos[row,2] == "") next # skip if no data is available for logo
  # Download pic and plot
  imgurl <- team_logos[row,2] # retrieve file url
  tmpfile <- tempfile(fileext = ".png") # define temporary save location
  download.file(url = imgurl, destfile = tmpfile, quiet = TRUE, mode = "wb") # download logo

  # Raster
  x <- plot[row,]
  x_rast <- rasterpic_img(x, tmpfile, crop = TRUE, mask = TRUE) # define variable for png
  actual_map <- actual_map + layer_spatial(x_rast) # add logo to map
}

# Download logos not added automatically to plot, due to faulty geom data from naturalearth
psg <- readPNG("data/logos_extra/psg.png", native = TRUE) # load image for graph
ajax <- readPNG("data/logos_extra/ajax.png", native = TRUE) # load image for graph
barcelona <- readPNG("data/logos_extra/barcelona.png", native = TRUE) # load image for graph
porto <- readPNG("data/logos_extra/porto.png", native = TRUE) # load image for graph

# Add logo of PSG
actual_map_comp <- actual_map +
    xlim(-20, 55) +
    ylim(35, 70) +
    theme(axis.text = element_blank(),
          panel.background = element_blank()) +
    inset_element(p = psg,
                 left = 0.24,
                 bottom = 0.29,
                 right = 0.4,
                 top = 0.41) +
    theme(rect  = element_rect(fill="transparent", linetype = "blank"))

# Add logo of Ajax
actual_map_comp <- actual_map_comp + 
  inset_element(p = ajax,
                 left = 0.335,
                 bottom = 0.48,
                 right = 0.375,
                 top = 0.52) +
  theme(rect  = element_rect(fill="transparent", linetype = "blank"))
  
# Add logo of Barcelona
actual_map_comp <- actual_map_comp +   
    inset_element(p = barcelona,
                 left = 0.205,
                 bottom = 0.07,
                 right = 0.285,
                 top = 0.3) +
    theme(rect  = element_rect(fill="transparent", linetype = "blank"))

# Add logo of FC Porto
actual_map_comp <- actual_map_comp +
    inset_element(p = porto,
                 left = 0.165,
                 bottom = 0.18,
                 right = 0.215,
                 top = 0.21) +
    theme(rect  = element_rect(fill="transparent", linetype = "blank"))

actual_map_comp

# Save plot
ggsave(
  plot = actual_map_comp,
  filename = "map_best_teams.png",
  bg = "transparent"
)

# Create table of SPI values of top teams per country in order
spi_table <- team_spi_top %>% 
  select(name, spi) %>% 
  rename("Country" = "name", "SPI" = "spi") %>% 
  arrange(desc(SPI))
```

