---
title: 'Visualisation '
author: "Madalina Dumitrescu"
date: "`r Sys.Date()`"
output:
  pdf_document:
    toc: yes
  html_document:
    theme: flatly
    highlight: zenburn
    number_sections: yes
    toc: yes
    toc_float: yes
---

## Setting up

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  message = FALSE, 
  warning = FALSE, 
  tidy=FALSE,     # display code as typed
  size="small")   # slightly smaller font for code
options(digits = 3)

# default figure size
knitr::opts_chunk$set(
  fig.width=30, 
  fig.height=15,
  fig.align = "center"
)
```

# Loading the libraries

```{r libraries, include=FALSE, echo = FALSE}
library(tidyverse)
library(extrafont)
library(vroom)
library(ggtext)
library(gapminder)
library(ggrepel)
library(patchwork)
library(gghighlight)
library(skimr)
library(ggridges)
library(maps)
library(reshape2)
library(rgdal)
library(lubridate)
library(ggforce)
library(tidyr)
library(dplyr)
library(countrycode)
library(ggflags)
library(png)
library(grid)
library(sf) # for geospatial visualisation
#read csv file
data_dir <- "~/Desktop/LBS/am10-group8-football-project/data/transfer"

files <- fs::dir_ls(path = data_dir, regexp = "\\.csv$", recurse = TRUE) 
#recurse=TRUE will recursively look for files further down into any folders

#read them all in using vroom::vroom()
football_transfer <- vroom(files, id = "source")
# Use janitor to clean names, and add more variables
football_transfer_all <- football_transfer %>%
  janitor::clean_names()  

# skimr::skim() to inspect and get a feel for the data         
skim(football_transfer_all)

#create df to select only the most expensive transfer/year since 1990
top_football_transfers <- football_transfer_all %>% 
  drop_na(fee_cleaned) %>% 
  filter(year > 1999) %>% 
  group_by(year) %>% 
  slice(which.max(fee_cleaned)) %>% 
  select(year, fee_cleaned, player_name)

#create a list of the nationalities of each transfer (because the information was not available)
nationality <- c("Portugal", "France", "United Kingdom", " United Kingdom", "Ivory Coast",
                 "Ghana", "Ukraine", "Spain", "Brazil", "Portugal", "Spain", "Argentina",
                 "Brazil", "United Kingdom", "Uruguay", "Belgium", "France", "Brazil", "France", 
                 "Portugal", "Germany", "United Kingdom")

#add the nationality column to the df and convert it to iso2c codes
top_football_transfers$nationality <- nationality 
top_football_transfers$iso3 <-countrycode(top_football_transfers$nationality ,"country.name", "iso2c")
top_football_transfers$iso3  <- tolower(top_football_transfers$iso3 )

#create the annotation for the first outlier and upload the image
annotation1 <- data.frame(
   x = 2009,
   y = 110,
   label = c("Cristiano Ronaldo \n Real Madrid -> Manchester United"))
img1 <- readPNG("C:/Users/ty/Desktop/LBS/am10-group8-football-project/data/transfer/ronaldo.png")
r <- rasterGrob(img1, interpolate=TRUE)

#create the annotation for the second outlier and upload the image
annotation2 <- data.frame(
   x = 2017,
   y = 240,
   label = c("Neymar \n  Barcelona FC -> PSG"))
img2 <- readPNG("C:/Users/ty/Desktop/LBS/am10-group8-football-project/data/transfer/neymar.png")
n <- rasterGrob(img2, interpolate=TRUE)

#create the annotation for the third outlier and upload the image
annotation3 <- data.frame(
   x = 2020,
   y = 110,
   label = c("Kai Havertz \n Bayer  \n Leverkusen \n -> Chelsea "))
img3 <- readPNG("C:/Users/ty/Desktop/LBS/am10-group8-football-project/data/transfer/kai.png")
k <- rasterGrob(img3, interpolate=TRUE)


  top_football_transfers$color <- ifelse(top_football_transfers$year == "2009" | top_football_transfers$year == "2017" | top_football_transfers$year == "2020", '#2a7e19', '#825736')


v <- top_football_transfers %>%
  ggplot(aes(x = year, y = fee_cleaned))+
  #geom_bar(stat = "identity", color = 'green', fill = '#2a7e19') +
  geom_bar(stat = 'identity', aes(fill = color), width = 0.6) +
  scale_fill_manual(values=c('#2a7e19', '#C5C5C5')) +
  #add flags to the graph
  geom_flag(y = -1, aes(country = iso3), size = 50) +
  #add limits to the x and y axis
  ylim(0,300) +
  scale_x_continuous(breaks = seq(2000,2021,1))+
  #set the theme, and add the annotations 
  theme_bw()+
  theme(aspect.ratio = 10/29,
    panel.grid = element_blank(),
    legend.title = element_blank(),
    legend.text  = element_blank(),
    legend.position="none",
    panel.border = element_blank(),
    panel.background = element_blank(),
    plot.title = element_text(family = "Arial",
                              size = 60, 
                              colour = "#222222", 
                              face = 'bold',
                              hjust = 0,
                              vjust = 2),   
    plot.subtitle = element_text(family = "Arial",
                                 size = 40,
                                 face = 'plain',
                                 colour = "#222222", 
                                 hjust = 0,
                                 vjust = 2),
    axis.text = element_text( size= 40, margin = margin(t = 100)),
    axis.title = element_text(size = 40)) +
    geom_text(data=annotation1, 
              aes(x=x, y =y, label=label),                 , 
              color="black", 
              size=15 , 
              angle=0, 
              fontface="bold") +
    annotation_custom(grob = r, 
                      xmin = 2008, 
                      xmax = 2010, 
                      ymin = 125, 
                      ymax = 165) +
    geom_text(data=annotation2, 
              aes( x=x, y =y,  label=label),                 , 
              color="black", 
              size=15 , 
              angle=0, 
              fontface="bold" ) +
    annotation_custom(grob = n, 
                      xmin = 2016, 
                      xmax = 2018, 
                      ymin = 250, 
                      ymax = 290) +
    geom_text(data=annotation3, 
              aes( x=x, y =y, label=label),                 , 
              color="black", 
              size=15 , 
              angle=0, 
              fontface="bold" ) +
    annotation_custom(grob = k, 
                      xmin = 2019, 
                      xmax = 2021, 
                      ymin = 140, 
                      ymax = 170) +
    labs( title = "Since 2013, the football transfer market has become more volatile compared to the early 2000's",
          subtitle = "The most expensive football transfers of each year and the player's nationalities", 
          citation = " ", 
          x = "",
          y = "Total transfer fee (€ millions)")

v

 
```


